# Lecture 1: Introduction to Machine Learning

## Learning Objectives

After completing Lecture 1, I should be able to:

1. Understand what Machine Learning is.
2. Differentiate between Supervised, Unsupervised and Reinforcement Learning.
3. Identify features and labels in a dataset.
4. Classify a problem as Regression, Classification, Clustering or Reinforcement Learning.

## Supervised Learning Examples:

In [2]:
import pandas as pd

house_data = {
    "Area": [1000,1200,1500],
    "Price": [20,24,30]
}

df = pd.DataFrame(house_data)

df

   Area  Price
0  1000     20
1  1200     24
2  1500     30

Features:
- Area
- Bedrooms

Label:
- Price

Problem Type:
- Regression

In [4]:
student_data = {
    "Study Hours": [1, 2, 3, 7, 8, 9],
    "Result": ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass"]
}

students = pd.DataFrame(student_data)

students

   Study Hours Result
0            1   Fail
1            2   Fail
2            3   Fail
3            7   Pass
4            8   Pass
5            9   Pass

Feature:
- Study Hours

Label:
- Result

Problem Type:
- Classification

# Unsupervised Learning Example:

In [5]:
customer_data = {
    "Annual Income": [20000, 25000, 100000, 120000],
    "Spending Score": [20, 25, 90, 95]
}

customers = pd.DataFrame(customer_data)

customers

   Annual Income  Spending Score
0          20000              20
1          25000              25
2         100000              90
3         120000              95

No labels are available.

The goal is to discover hidden groups of customers.

Problem Type:
- Unsupervised Learning

# Reinforcement Learning Example:

In [6]:
reward = 10

if reward > 0:
    print("Good Action -> Reward Received")
else:
    print("Bad Action -> Penalty")

Good Action -> Reward Received

Examples:
- Self-Driving Cars
- Robotics
- Game Playing AI

The agent learns using rewards and penalties.

### Key Learnings from Lecture 1

1. Machine Learning learns patterns from data.
2. Supervised Learning uses labeled data.
3. Regression predicts numerical values.
4. Classification predicts categories.
5. Unsupervised Learning discovers hidden patterns.
6. Reinforcement Learning learns through rewards and penalties.

Most ML projects start by identifying:
- Features
- Labels
- Problem Type